default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  host: localhost
  username: rubyadmin
  password: password

development:
  <<: *default
  database: greenx_development

#test:
#  <<: *default
#  database: greenx_test

production:
  <<: *default
  username: green_x
  password: P@$$w0rd123
  database: greenx_prod
