development:
  <<: *default
  
production: &default

  client_id: Ad2Q9Al8XyhBW_bW3pLCaDPP-ZwHrwLkVedI6yDaH7edhSaljEPaeH2uPIVF5FKYFBpifMOPI7ijRtng
  client_secret: EFxNQHwoNbTyQgS2FMQ9n3z2KmCly61I0OafJc3Fpwn-YhgwY3tMoYFmEeMkaDX6rH6wDrsBTnCiY1-T
  mode: live
